# Prerequisites
# 1. Create a branch called gh-pages
# 2. Create a GitHub Personal access token - https://github.com/settings/tokens - with public_repo permission
# 3. Set GITHUB_TOKEN, GITHUB_EMAIL and GITHUB_USERNAME on Travis CI settings (or encrypt them locally and set them into .travis.yml file)

language: node_js
node_js:
  - 8

env:
  global:
    # travis encrypt GITHUB_TOKEN=....
    - secure: "HhiaLApIqssh53fOEpBfGmnfUKWEM5Fy714PwHElawH+XpVEG34ouvkCoTLWcZ1J/wGSI1wopHiK26LrhJzdlurw1CmhiN+iceyX3Zd6K4Q0S0tJja7UgACYQis/T/Eot5nS+VGsEW/eZVaLiEfj5mkPwGIdNfVDZdbWysXjf9XqPLbRje7Su3gQEyrdUkExAzw42DH/+XvlXdzpB2Fbh/oRaHZZl0/BUXxMbMHmSVx6k6kzGRK10JSjkcTgEz10fnUK9/9h40VQIWJLJb0RM0/Ujxh1/eZB2pqNc9y9cRNiYARpN9xukn8JNxokAOYytAmKfouEXDHrDeNlKSYwFG+bkzaw+E796WCizCpIC6FydHZpEbTIBNySrs3ET9a0tQcY8WfW4wjzufZwMk9hkpDDb1B0Q1nq1akntIkR86Hfv5Yr5feofyDx3i/vZH2qPsvKQK7uls+eRMOqM0XtQYhCvOoPVl6eYynqLU6gsARCTESxwqSp/gAAq0/73ajq4xqGCSFWaZyh2/+F7eXdQuzDf8mG6F6bLftTmlwKEf9VYE5+XMNk1t2QbCa1WnLlYPRgJ722Nx7SeqTK3kh5PlQNeGRwYwaxBgXkfEi4H+S5EBtwrp+W4mROMCh8mjevLy528Fm0wYN2ee01vdgEDBO76KYS+61e4vttpA6McDM="
    # travis encrypt GITHUB_USERNAME=....
    - secure: "EixhTy5mAtSm4nLMW1/YWUabQJZ770ndVF3o8mAynkYxpWyqF+pDAfC4rIXjKA88tgQcIjadn18G8yIEtaKCDbbFAtZEwTgdHuzig2t0Wg2NUiO4DAgV2NnBLUHLg5kpBxWyn5GK7jJ+/Q9zNErf6H7DmlX3SMMeFgv61JgFr0QIY/xn/3AZZuSAmnhkkCAv8IPUvZQyQ9SJI3Om+x1XxOspCIt7eFgFexqwWDrCwx+gM/xhdDas1KvgDIMADbwY6YFj+krfk93QitmcfHnGPKaZxrwWrlnfS+3JdQwYxivtIfumLGk2meDCSU47uzfwm3Bzm9Hi9ep7KYQS5XamZxWP4qdjAijr+V/qnG9bNfueoYuhFcSpUNzb5woQsb7wfWKtZ/GGd+eCxwcgR7kSyVnM68mEOnCNWoPRjWJrQGA3CRL1A6dEOCS6gGb3EGYRfVchQq56AHlPyD41l2CP2ZE5siqPRSseupVou/NBtsKE25Rfvfhv19cAb4jxfrstzjwkG9K+rGpjNVBd9FPRhaoC0G8Tx3O9o6ojPYrKSrx33z9kZlN7nBOVQF1X7m5yOTqUYNXZvMAqjnQSCuBbbFRj99j0DS80GNXD2X0cjIER8KUjhL4s4MwvjJoo1xJZew+wAg7rDPQKDsYHTzmAkgQp2ziGuqhDTkWw99Illr4="
    # travis encrypt GITHUB_USERNAME=....
    - secure: "LMaCu1hr+f1cR0YfHnlI5qg/Hi3wLSUehgd03BAvxhqd2xOGxwQQ3sLp5FFAtgATSrvh3atOjfuaTVLY54XDDqHVbEn3O+obuvSwPiKc5QExMj0kctjo8rPKxnQX77raRnnwjT90N3tKAN0N7w0KbgjaHOyzU+xSvnjbzNMzJfmSzSga12rAOymtpz/cQP/MgRrGtx4/vy/rpIKcSMCADWtQTU6jaebiYMsXgoeuq9p7Xu9hYVEt5cRIC+NzSpntgCOkUNIqsHCIkuMQdimzSb0Gqx+YuDH+2o5fDzvhrlsEIE9bVXW9q6iZWCXH0P+gRADSrDhqvmRqjYOMgM/dLwhbLQSOzW/OWl1fIG+XJyxTC7VGZU1lWAhS7WiSLSIB4E0rKjZIxTQU0wOkSSX0qqPGQs7ZheMXY5V8+eRhao8yJmjTi/HhJV+Z3Z+jmfqh0HDucc5Mky41eaptUQA/ehx50ZroKZGrbva6su1XbGX6w6JUTj4oc/B4YQnyOtMBQY/G/BjfonL84p2lZormW+2lXqYoHkIfPHumFsTgQleMuHMyB6NOdssZgTSjdiezSrO1Un+gH+JjidkF20fwwRISmA6Y9DpvxnCZoUye5DUhKjbYK83VHOHJW88YyzhUNrYoVqIlyCWQF7YauI4vC4+CBIwWfraU4LyPaBWog4M="

# Generate typedoc into the docs folder
script:
  - npm install -g yarn
  - yarn install
  - yarn test
  - yarn run doc
  - TRAVIS_TAG=blah ; sed -i "s/\[\[tag\]\]/$TRAVIS_TAG/g" docs/_config.yml
  - cat docs/_config.yml

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  email: $GITHUB_EMAIL
  name: $GITHUB_USERNAME
  verbose: true
  keep-history: true
  local-dir: docs
  target_branch: gh-pages
  on:
    branch: master
    # TODO - Enable when ready for release
    # tags: true