theme: jekyll-theme-slate

title: FINOS FDC3 API specifications
description: The documentation website for the FINOS FDC3 API specifications

google_analytics: UU-123456

show_downloads: true

github:
  zip_url: https://fdc3.org
  tar_url: https://fdc3.org
  is_project_page: true
  repository_url: https://github.com/fdc3/api